title: Code to Learn
description: >- # this means to ignore newlines until "baseurl:"
  My Learning Journey
baseurl: '/blog' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

repository: nkadebug/blog

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
